[build]
  command = "dotnet publish -c Release -o release"
  environment = { NETCORE_VERSION = "8.0" } # Use the version that supports .NET 8.0


[[redirects]]
from = "/*"
to = "/index.html"
status = 200